services:
  szurubooru-manager:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    container_name: szurubooru-manager
    restart: unless-stopped
    
    # Volume mounts
    volumes:
      # Mount your upload directory
      - ./uploads:/app/uploads:ro
      # Mount logs directory for persistence
      - ./logs:/app/logs
      # Mount config file for easy updates
      - ./config.json:/app/config.json:ro
      # Optional: mount processed files tracking
      - ./processed_files.json:/app/processed_files.json
    
    # Environment variables (can override config.json)
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
      # Override config values if needed
      # - SZURUBOORU_URL=http://your-szurubooru-instance:8080
      # - USERNAME=your-username
      # - API_TOKEN=your-api-token
    
    # Network settings
    networks:
      - szurubooru-network
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/szurubooru_manager.py') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  szurubooru-network:
    driver: bridge
